---
version: "3"
services:
  op:
    container_name: op_latex_build
    image: leplusorg/latex
    volumes:
      - .:/data
    entrypoint: [ "pdflatex", "--enable-write18 ", "op-resume.tex" ]
    working_dir: "/data"
