name: Build Resumes
on:
  push:
    branches: [main]
jobs:
  main:
    name: Build Main Resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: bdepalo-bdepalo-resume.tex
      - name: Upload Resume
        uses: actions/upload-artifact@v3
        with:
          name: Resume
          path: bdepalo-resume.pdf
  short:
    name: Build Short Resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: bdepalo-short-bdepalo-resume.tex
      - name: Upload Resume
        uses: actions/upload-artifact@v3
        with:
          name: Short Resume
          path: bdepalo-short-resume.pdf