name: Build Resumes
on:
  push:
    branches: [main]
jobs:
  main:
    name: Build Resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: op-resume.tex
      - name: Upload Resume
        uses: actions/upload-artifact@v3
        with:
          name: Resume
          path: op-resume.pdf